{
 "title": "Mapa",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mapa de Consumos",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "union(\n    tables: [\n        from(bucket: \"med_samborondon\")\n            |> range(start: -1m)\n            |> filter(fn: (r) => r._measurement == \"mediciones\" and (r._field == \"lat\" or r._field == \"lon\" or r._field == \"consumo_kwh\"))\n            |> group(columns: [\"id_medidor\", \"_field\"])\n            |> last()\n            |> pivot(rowKey: [\"_time\", \"id_medidor\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n            |> map(fn: (r) => ({\n                region: \"Samborondon\",\n                medidor: r.id_medidor,\n                lat: r.lat,\n                lon: r.lon,\n                consumo: r.consumo_kwh,\n                time: r._time\n            })),\n\n        from(bucket: \"med_daule\")\n            |> range(start: -1m)\n            |> filter(fn: (r) => r._measurement == \"mediciones\" and (r._field == \"lat\" or r._field == \"lon\" or r._field == \"consumo_kwh\"))\n            |> group(columns: [\"id_medidor\", \"_field\"])\n            |> last()\n            |> pivot(rowKey: [\"_time\", \"id_medidor\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n            |> map(fn: (r) => ({\n                region: \"Daule\",\n                medidor: r.id_medidor,\n                lat: r.lat,\n                lon: r.lon,\n                consumo: r.consumo_kwh,\n                time: r._time\n            }))\n    ]\n)\n|> keep(columns: [\"region\", \"medidor\", \"lat\", \"lon\", \"consumo\", \"time\"])\n"
    }
   ]
  },
  {
   "title": "Consumo Promedio en Samborondon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"med_samborondon\")\n  |> range(start: -1h) // Últimas 24 horas\n  |> filter(fn: (r) => r._measurement == \"mediciones\" and r._field == \"consumo_kwh\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) \n  |> group(columns: [\"region\"]) \n  |> keep(columns: [\"_time\", \"region\", \"_value\"]) \n  |> rename(columns: {_value: \"promedio_consumo\"}) \n\n\n\n"
    }
   ]
  },
  {
   "title": "Consumo Promedio en Daule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"med_daule\")\n  |> range(start: -1h) \n  |> filter(fn: (r) => r._measurement == \"mediciones\" and r._field == \"consumo_kwh\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) \n  |> group(columns: [\"region\"]) \n  |> keep(columns: [\"_time\", \"region\", \"_value\"]) \n  |> rename(columns: {_value: \"promedio_consumo\"}) \n\n\n"
    }
   ]
  }
 ]
}